package LockerData.entity;
// Generated Feb 19, 2018 4:28:01 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Customers generated by hbm2java
 */
public class Customers  implements java.io.Serializable {


     private Integer id;
     private String fullName;
     private String fname;
     private String lname;
     private String address;
     private String city;
     private String state;
     private String zip;
     private Date dateEntered;
     private String phone;
     private String workPhone;
     private String cellPh;
     private String notes;
     private String ssn;
     private Date dob;
     private Date badCheck;
     private Date approvedDate;
     private String email;

    public Customers() {
    }

	
    public Customers(String zip) {
        this.zip = zip;
    }
    public Customers(String fullName, String fname, String lname, String address, String city, String state, String zip, Date dateEntered, String phone, String workPhone, String cellPh, String notes, String ssn, Date dob, Date badCheck, Date approvedDate, String email) {
       this.fullName = fullName;
       this.fname = fname;
       this.lname = lname;
       this.address = address;
       this.city = city;
       this.state = state;
       this.zip = zip;
       this.dateEntered = dateEntered;
       this.phone = phone;
       this.workPhone = workPhone;
       this.cellPh = cellPh;
       this.notes = notes;
       this.ssn = ssn;
       this.dob = dob;
       this.badCheck = badCheck;
       this.approvedDate = approvedDate;
       this.email = email;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }
    public Date getDateEntered() {
        return this.dateEntered;
    }
    
    public void setDateEntered(Date dateEntered) {
        this.dateEntered = dateEntered;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getWorkPhone() {
        return this.workPhone;
    }
    
    public void setWorkPhone(String workPhone) {
        this.workPhone = workPhone;
    }
    public String getCellPh() {
        return this.cellPh;
    }
    
    public void setCellPh(String cellPh) {
        this.cellPh = cellPh;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public String getSsn() {
        return this.ssn;
    }
    
    public void setSsn(String ssn) {
        this.ssn = ssn;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public Date getBadCheck() {
        return this.badCheck;
    }
    
    public void setBadCheck(Date badCheck) {
        this.badCheck = badCheck;
    }
    public Date getApprovedDate() {
        return this.approvedDate;
    }
    
    public void setApprovedDate(Date approvedDate) {
        this.approvedDate = approvedDate;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


